apiVersion: apps/v1
kind: Deployment            # telling Kubernetes to create a Deployment, which ensures that a specified number of pod replicas are running and updated automatically.
metadata:                   # sets the name of the deployment object in Kubernetes. It's used to identify and manage this deployment.
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: restapp
            - name: MYSQL_DATABASE
              value: user_db
            - name: MYSQL_USER
              value: restuser
            - name: MYSQL_PASSWORD
              value: restpass
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}  # Use persistentVolumeClaim for production
