# This file mysql-service, exposes the sql service by the name 'mysql-service' in the cluster.
# connecting to sql by the flask service , will be by using the host name: mysql-service and port 3306 in the cluster.
apiVersion: v1  # Chart's format
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
