apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: rest-app-service
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
