services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: restapp
      MYSQL_DATABASE: user_db
      MYSQL_USER: restuser
      MYSQL_PASSWORD: restpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  rest_app:
    image: walaahij/rest-app-server:BUILD_ID_PLACEHOLDER
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: restuser
      DB_PASSWORD: restpass
      DB_NAME: user_db
    ports:
      - "5000:5000"

volumes:
  mysql_data:
