apiVersion: v2          # Chart's format
name: restapp-chart
description: A Helm chart for deploying the Flask-based rest app
type: application       #  an application (not a library chart).
version: 0.1.0          #  Version of the chart